services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis-server'
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redis-insight:
    image: 'redis/redisinsight:latest'
    container_name: 'redis-insight'
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redis-insight:/data
    depends_on:
      - redis

  api:
    image: atc-challenge:development
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      ATC_BASE_URL: http://mock:4000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  mock:
    image: atc-challenge:development
    command: node /usr/src/app/mock/server.js
    volumes:
      - ./mock:/usr/src/app/mock
    ports:
      - 4000:4000
    environment:
      EVENT_INTERVAL_SECONDS: 10
      REQUESTS_PER_MINUTE: 20
      EVENT_PUBLISHER_URL: http://api:3000/events
    depends_on:
      - api

volumes:
  redis_data:
  redis-insight:
