services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '3000:3000'
    environment:
      ATC_BASE_URL: http://mock:4000

  mock:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: node /usr/src/app/mock/server.js
    volumes:
      - ./mock:/usr/src/app/mock
    ports:
      - '4000:4000'
    environment:
      EVENT_INTERVAL_SECONDS: 10
      REQUESTS_PER_MINUTE: 60
      EVENT_PUBLISHER_URL: http://api:3000/events
